### ISSUE TITLE
Ampersand symbol

### ISSUE THREAD

**Issue by jim-rosales** [pollysiegel/colmar-academy#2]
For special symbols such as the ampersand, you should use its [entity reference](https://developer.mozilla.org/en-US/docs/Glossary/Entity). 

In this case, you'd replace the `&` with `&amp;`

https://github.com/pollysiegel/colmar-academy/blob/f824f4f1aa5b28fe4661da4f2241e47736a5b8ce/index.html#L91

**Comment by pollysiegel** [comment]
Oooh. Good point -- I missed that!  I've fixed all occurrences (ampersand and copyright symbol).
